development:
  adapter: postgresql
  host: localhost
  username: user
  database: band-rater-development

test:
  adapter: postgresql
  host: localhost
  username: user
  database: band-rater-test

production:
  adapter: postgresql
  host: localhost
  username: user
  database: band-rater-production
